language_list = [
    "English",
    "Svenska",
    "Deutsch",
    "No language",
    "日本語",
    "Français",
    "Español",
    "العربية",
    "Latin",
    "ភាសាខ្មែរ",
    "Tiếng Việt",
    "Türkçe",
    "ελληνικά",
    "普通话",
    "Pусский",
    "Gaeilge",
    "广州话 / 廣州話",
    "Magyar",
    "עִבְרִית",
    "नेपाली",
    "සිංහල",
    "Italiano",
    "Nederlands",
    "Suomi",
    "Português",
    "Gàidhlig",
    "فارسی",
    "اردو",
    "Dansk",
    "ภาษาไทย",
    "Norsk",
    "Shqip",
    "Polski",
    "Íslenska",
    "Tagalog",
    "ਪੰਜਾਬੀ",
    "हिन्दी",
    "қазақ",
    "български",
    "Kiswahili",
    "Română",
    "한국어조선말",
    "Český",
    "Slovenčina",
    "Māori",
    "Esperanto",
    "Somali",
    "Afrikaans",
    "isiXhosa",
    "isiZulu",
    "ייִדיש",
    "Català",
    "српски",
    "संस्कृतम्",
    "Український",
    "Hrvatski",
    "Galego",
    "Српскохрватски",
    "Corsu",
    "Kernewek",
    "བོད་ཡིག",
    "Bosanski",
    "پښتو",
    "ᐃᓄᒃᑎᑐᑦ",
    "Հայերեն լեզու",
    "አማርኛ",
    "нохчийн мотт",
    "Eesti",
    "كوردی",
    "Diné bizaad",
    "монгол хэл",
    "Faka-Tonga",
    "বাংলা",
    "chiCheŵa",
    "seSotho",
    "རྫོང་ཁ",
    "Cymraeg",
    "Wolof",
    "ქართული",
    "Brezhoneg",
    "தமிழ்",
    "Bahasa indonesia",
    "മലയാളം",
    "తెలుగు",
    "кыргыз тили",
    "Bamanankan",
    "Slovenščina",
    "Norsk Bokmål"
]
